// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANGjfRnFK-GCyoBrThS1xeYLxA8muQ20s',
    appId: '1:333980362825:web:3facb05707fad9c3fc7798',
    messagingSenderId: '333980362825',
    projectId: 'sky-chatter',
    authDomain: 'sky-chatter.firebaseapp.com',
    storageBucket: 'sky-chatter.appspot.com',
    measurementId: 'G-K98YJJMPSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWYN468Sr6TkMWpMRT39xP_cQQcG78DgI',
    appId: '1:333980362825:android:d02a0b3f056776d7fc7798',
    messagingSenderId: '333980362825',
    projectId: 'sky-chatter',
    storageBucket: 'sky-chatter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNeAMZchFGImnjRhLfOl0Vj3h6XVz5WD8',
    appId: '1:333980362825:ios:52207fecc675de5afc7798',
    messagingSenderId: '333980362825',
    projectId: 'sky-chatter',
    storageBucket: 'sky-chatter.appspot.com',
    iosClientId: '333980362825-ehkgka151m5usjkhnh0tfcu3vm8un763.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbla2223Project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNeAMZchFGImnjRhLfOl0Vj3h6XVz5WD8',
    appId: '1:333980362825:ios:52207fecc675de5afc7798',
    messagingSenderId: '333980362825',
    projectId: 'sky-chatter',
    storageBucket: 'sky-chatter.appspot.com',
    iosClientId: '333980362825-ehkgka151m5usjkhnh0tfcu3vm8un763.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbla2223Project',
  );
}
